[package]
name = "apod_desktopv2"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
env_logger = "0.11.8"
little_exif = "=0.6.23"
serde = {version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
ureq = {version = "3.1.4", features = ["json"] } 
xdg = "3.0.0"
